//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueOceanSeminarska.App_Start
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlueOceanDBEntities : DbContext
    {
        public BlueOceanDBEntities()
            : base("name=BlueOceanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PoslaniPodatki> PoslaniPodatki { get; set; }
        public virtual DbSet<Spins> Spins { get; set; }
        public virtual DbSet<BiggestWins> BiggestWins { get; set; }
    }
}
