//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueOceanSeminarska.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiggestWins
    {
        public int Id { get; set; }
        public string RemoteId { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
    }
}
