//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueOceanSeminarska.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoslaniPodatki
    {
        public int Id { get; set; }
        public string auth_usr { get; set; }
        public string remote_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string game_id { get; set; }
        public string game_session_id { get; set; }
        public string currencycode { get; set; }
        public string round_id { get; set; }
        public Nullable<bool> final { get; set; }
        public Nullable<bool> is_bonus_win { get; set; }
        public Nullable<bool> is_freeround_bet { get; set; }
        public Nullable<bool> is_freeround_win { get; set; }
        public Nullable<bool> is_jackpot_win { get; set; }
        public Nullable<bool> is_rollback { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string nickname { get; set; }
        public string platform_id { get; set; }
        public string agent_id { get; set; }
        public string agent_prefix { get; set; }
        public string group { get; set; }
        public Nullable<System.DateTime> DatumZapisa { get; set; }
    }
}
